name: yandex_maps_mapkit_lite
description: Yandex MapKit lite SDK for Flutter. This allow you to use the capabilities
  of Yandex.Maps in your Flutter applications for iOS and Android
version: 4.22.0-beta
repository: https://github.com/yandex/yandex_maps_mapkit_lite
environment:
  sdk: ^3.1.0
  flutter: '>=3.29.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  uuid: ^4.2.2
  flutter_plugin_android_lifecycle: ^2.0.16
  meta: ^1.9.1
dev_dependencies:
  build_runner: ^2.6.0
  source_gen: ^3.0.0
  init:
    path: codegen/init
flutter:
  plugin:
    platforms:
      android:
        package: com.yandex.maps.flutter
        pluginClass: YandexMapsPlugin
      ios:
        pluginClass: YandexMapsPlugin
