export 'package:yandex_maps_mapkit_lite/src/mapkit/geometry/geometry.dart'
    hide
        GeometryContainerExtension,
        GeometryNativeData,
        GeometryNative,
        PolygonContainerExtension,
        SubpolylineContainerExtension,
        PolylineContainerExtension,
        SegmentNative,
        PolylinePositionNative,
        PolylinePositionContainerExtension,
        MultiPolygonContainerExtension,
        SegmentContainerExtension,
        CircleNative,
        LinearRingContainerExtension,
        CircleContainerExtension,
        SubpolylineNative,
        BoundingBoxNative,
        BoundingBoxContainerExtension;
